README.md, exporter.py
This adds the possibility to use authentication against the MQTT broker.
=> Authentication

exporter.py
Could be useful to see which sensors are sending data and which are not (e.g. when outside of range)
=> Now exposing a counter of received messages

README.md, exporter.py
Parameterises the MQQT subscription topic
Use `MQQT_TOPIC` environment variable to configure the subscription topic.
=> Parameterise mqtt topic

exporter.py
Issues with some parameters type when set using varenvs.
=> Fix parameter cast to integer

README.md, TODO, exporter.py
=> Feature: Add ability to ignore topics.

.pre-commit-config.yaml, mqtt_exporter/main.py, requirements/dev.txt
Add support for devices that expose a ON/OFF value. This is the case for several switch. This proposal maps ON to 1 and OFF to 0 when exporting the metrics.
=> Add support for ON/OFF state

mqtt_exporter/main.py
I've got a new device that emits a metric where the value is either of the strings `true` or `false`. So I'm adding them to the `STATE_VALUES` like `on`/`off` before.
=> Adding support for True/False

mqtt_exporter/main.py
Added support for more complex(nested) MQTT messages, as some devices publish nested contents (for example Tasmota).
To handle this, the metrics are recursively get parsed, to extract all metrics from a message.
An example would be this MQTT message:
``` JSON
{
"Time": "2021-10-03T11:05:21",
"ENERGY": {
"Total": 152.657,
"Yesterday": 1.758,
"Today": 0.178,
"Power": 143,
"ApparentPower": 184,
"ReactivePower": 117,
"Factor": 0.77,
"Voltage": 235,
"Current": 0.784
}
}
```
It will parse into:
```
mqtt_ENERGY_Total
mqtt_ENERGY_Yesterday
mqtt_ENERGY_Today
mqtt_ENERGY_Power
mqtt_ENERGY_ApparentPower
mqtt_ENERGY_ReactivePower
mqtt_ENERGY_Factor
mqtt_ENERGY_Voltage
mqtt_ENERGY_Current
```
=> Support for nested MQTT messages

Dockerfile
Traefik for example will autodetect the port if there's an expose declaration. 
Thanks for your consideration!
=> expose default port in dockerfile

docker-compose.dev.yml
see https://github.com/kpetremann/mqtt-exporter/pull/29#discussion_r911740566
for background information
=> add docker-compose for development purposes using build instead of image

README.md, mqtt_exporter/main.py, mqtt_exporter/settings.py, tests/functional/test_parse_message.py, tests/functional/test_parse_metrics.py
Add zwavejs2mqtt support
Solves #28
=> Zwavejs2mqtt support

README.md, mqtt_exporter/main.py, mqtt_exporter/settings.py, tests/functional/test_parse_message.py
KEEP_FULL_TOPIC varenv must be set to "True"
Fixes #36
=> Add support for Shelly 3EM

.github/workflows/main.yml
=> Publish image to GHCR and Dockerhub

mqtt_exporter/main.py, mqtt_exporter/settings.py, tests/functional/test_parse_message.py
Implements: #57
Adds Hubitat support when used with [YAMA](https://community.hubitat.com/t/beta-yama-yet-another-mqtt-app/62219)
=> Hubitat support

exporter.py, mqtt_exporter/settings.py, tasks.py, tests/functional/test_parse_message.py, tests/functional/test_parse_metrics.py, tests/unit/test_normalize_prometheus_name.py
Black has been updated with new rules. This PR goal is to make the CI happy again.
=> style: apply new black rules

README.md
=> docs: update working list

mqtt_exporter/main.py, mqtt_exporter/settings.py
This PR is a replica of #52, with conflicts and CI fixes.
Original author: @Matthew-Beckett.
=> Support TLS with optional CA validation

.github/workflows/ci.yml, mqtt_exporter/main.py, pyproject.toml, tests/functional/test_parse_metrics.py
=> feat: remove old metrics when zigbee1mqtt renaming event

README.md, mqtt_exporter/main.py, mqtt_exporter/settings.py
Implement: config opttion to allow ignoring the msg-payload.
Thanks for the great exproter! I am using it since today and it works great!
Since we don't need metrics of the payload, i added a setting to be able to ignore it.
=> feat: allow ignoring msg payload

.github/workflows/docker-release.yml, .github/workflows/helm-release.yml
Related to #90
Fix gh action if statement + moving the helm chart releasing to a dedicated action.
=> fix(ci): invalid gh action for helm

mqtt_exporter/main.py
=> fix: metric references memory leak
