.github/workflows/main.yml
Unfortunately, the docker image `kpetrem/mqtt-exporter` has only one arch hence does not work under other architectures (e.g. on Raspberry PI). Adding this file to the repository will automatically build and publish images on dockerhub for all available architectures. No additional costs will apply as it's based on Github Actions.
Please change the last line of the `main.yml` to place the correct dockerhub username.
=> Adding GitHub action to publish multi-arch docker image

exporter.py
(Copied from https://github.com/kpetremann/mqtt-exporter/pull/8 )
Disclaimer: These are the first three lines of Python I've ever written.
I encountered a `UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte` when trying to use this exporter with data from my Xiaomi Roborock vacuum. It's probably the `map_data` which I don't care about anyway, so this was my fix.
=> Fix: Don't crash when not able to decode payload.

README.md, mqtt_exporter/main.py
This PR allows to define topics to ignore using wildcards (`*`, `?`) rather than requiring an exact match. This patch should be backwards-compatible as exact match should still happen if there are no wildcards present.
A single `*` will match across `/` separators: `*excludeme*` will exclude `foo/excludeme/bar`.
As a side note, I have fixed the env var being documented with an incorrect name in `README.md`.
=> main: match ignored topics with fnmatch instead of equality

README.md, mqtt_exporter/main.py, mqtt_exporter/settings.py
Zigbee2MQTT 1.24.0 added the possibility to configure device availability
payloads as a JSON object
https://www.zigbee2mqtt.io/guide/configuration/device-availability.html#availability-payload
=> Add Zigbee2MQTT device availability support (non-legacy mode only)

README.md, mqtt_exporter/main.py, mqtt_exporter/settings.py, requirements/tests.txt, tests/functional/test_expose_metrics.py
Feature request #24 
- MQTTv5 protocol support to have client ID auto generated
- be able to set client ID for any MQTT protocol version
- be able to expose client ID
The client ID will remain empty if client id = "" and MQTTv5 disabled.
=> Expose Clientid and add MQTT v5 support

mqtt_exporter/main.py, tests/functional/test_parse_message.py, tests/functional/test_parse_metrics.py
after fix:
INFO:mqtt-exporter:creating prometheus metric: z2m_DS18B20_1_Temperature
INFO:mqtt-exporter:creating prometheus metric: z2m_DS18B20_2_Temperature
before fix:
[...]
INFO:mqtt-exporter:creating prometheus metric: z2m_Dimmer1
INFO:mqtt-exporter:creating prometheus metric: z2m_Dimmer2
Traceback (most recent call last):
File "/opt/mqtt-exporter/exporter.py", line 5, in <module>
main()
File "/opt/mqtt-exporter/mqtt_exporter/main.py", line 202, in main
client.loop_forever()
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
rc = self._loop(timeout)
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
rc = self.loop_read()
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in …
=> fix "Invalid metric name" when topic contains »-«

README.md, mqtt_exporter/main.py, mqtt_exporter/settings.py
The goal of this PR is to make debugging easier, especially for support.
It logs in debug MQTT original topic and payload (disabled by default).
=> Debug: log MQTT message (optional)

mqtt_exporter/main.py, tests/functional/test_parse_metrics.py
This PR resolves the following exception
=> fix: Exception when metric key has a slash in it

.github/workflows/release.yml
Implements #34
Docker images are pushed with tags:
- "master" tag when only pushing or merging PR to the master
- "1.2.3", "1.2" and "1" tags when pushing a tagged version
=> Docker tags

.github/workflows/release.yml
only 1.2.3 was pushed, and not 1.2 nor 1
=> Fix missing tags

mqtt_exporter/main.py, tests/functional/test_parse_metrics.py
Shelly 3EM running Tasmota sends following. This patch enables mqtt-exporter to extract values from lists.
Before:
DEBUG:mqtt-exporter:Failed to convert Power: Can't parse '[148, 133, 106]' to a number.
Now:
DEBUG:mqtt-exporter:parsing list Power: [104, 133, 107]
DEBUG:mqtt-exporter:new value for mqtt_ENERGY_Power_0: 104
DEBUG:mqtt-exporter:new value for mqtt_ENERGY_Power_1: 133
DEBUG:mqtt-exporter:new value for mqtt_ENERGY_Power_2: 107
MQTT message:
{
"Time": "2023-01-28T01:08:31",
"ENERGY": {
"TotalStartTime": "2023-01-23T23:19:38",
"Total": 2.785,
"Yesterday": 1.748,
"Today": 1.037,
"TodaySumImport": 1.037,
"TodaySumExport": 0,
"ExportActive": [
0,
0,
0
],
"Period": [
12,
11,
9
],
"Power": [
97,
133,
107
],
"ApparentPower": [
153,
182,
214
],
"ReactivePower": [
118,
125,
186
], …
=> add support for parsing values containing lists

.github/workflows/ci.yml, .gitignore, mqtt_exporter/main.py, pylama.ini, pyproject.toml, requirements/dev.txt, requirements/tests.txt
Pylama does not seem to be maintained anymore (pydocstyle compatibility issues are not addressed etc...).
Plus, ruff is way more faster!
=> ci: migrate from pylama to ruff

mqtt_exporter/main.py
While trying to understand how some options worked, I noticed small typos in the code comments. This is a fix for that.
=> Fix small comment typos

mqtt_exporter/main.py, tests/functional/test_expose_metrics.py, tests/functional/test_parse_metrics.py, tests/unit/test_normalize_prometheus_name.py
Fixes/Implement: #64 
When using MQTTv5, attach any UserProperties from the message as labels on the exposed metrics.
=> Attach UserProperties as labels to metrics when using MQTTv5 protocol

mqtt_exporter/main.py
UserProperty is not always set, causing an unhandled exception. A better fix might be possible.
Fixes #66
note: the crash is only happening in MQTT_v5 mode
=> fix: userproperty exception

pyproject.toml
- top-level linter settings are deprecated
- ignoring bandit S104 rules: we authorize binding to all interfaces
=> ci: fix linter configuration

README.md, mqtt_exporter/main.py, mqtt_exporter/settings.py, pyproject.toml
Fixes/Implement: -
First, add some basic properties in `pyproject.toml` as laid out in the [Python Packaging guide](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/). This helps distribution and such to easier package mqtt-exporter. 
Hopefully these are okay as-is.
Second, add a new, pretty straight-forward `PROMETHEUS_ADDRESS` setting, to be able to specify the address mqtt-exporter should listen on.
Users might want their mqtt-exporter to e.g. just listen on localhost, thereby also reducing the risk of accidentally exposing it to the network.
Cheers,
Christoph
=> Add basic pyproject properties & `PROMETHEUS_ADDRESS` setting

README.md, mqtt_exporter/main.py
Add an interactive test mode in CLI, to test the conversion of a topic+payload to a Prometheus metric.
Usage example
```sh
$ python ./exporter.py --test
topic: zigbee2mqtt/0x00157d00032b1234
payload: {"temperature":26.24,"humidity":45.37}
parsed to: zigbee2mqtt_0x00157d00032b1234 {'temperature': 26.24, 'humidity': 45.37}
INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqtt_temperature', labels=())
INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqtt_humidity', labels=())
mqtt_temperature{topic="zigbee2mqtt_0x00157d00032b1234"} 26.24
mqtt_humidity{topic="zigbee2mqtt_0x00157d00032b1234"} 45.37
```
=> CLI: Test tool

mqtt_exporter/main.py, tests/functional/test_parse_message.py
Fixes/Implement: #82 
When parsing a message, check if it is one of the defined `STATE_VALUES`, and in that case, use that value instead of trying to parse using JSON.
**Before the commit:**
See the linked issue.
**After the commit:**
```
topic: freezer_open_detector/binary_sensor/freezer_open/state
payload: OFF
parsed to: freezer_open_detector_binary_sensor {'state': 0}
INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqtt_state', labels=())
mqtt_state{topic="freezer_open_detector_binary_sensor"} 0.0
```
=> Handle plain state value string in raw_payload

.github/workflows/release.yml
Fixes/Implement: #90
This PR adds a GitHub Action Workflow Job to publish the HelmChart that is already present in this repository. This Workflow Job will only run when a tag is pushed.
Before merging this Merge Request the used GitHub action requires that an empty branch called `gh-pages` is created and chosen for use with GitHub Pages in the repository settings.
After the first successful release with a chart, I will be opening a follow-up PR that will add the Helm repository to ArtifactHub.
P.S.: I have never implemented releasing charts with GitHub Actions and I have no idea how to test this PR before merging it. I am willing to do follow-up PRs if things should go south.
**Before the commit:**
HelmChart was only present in Git to deploy the application.
**After the …
=> feat: add helmchart publishing

.github/workflows/helm-release.yml
Fixes/Implement: #90 
Hopefully, this PR fixes the if condition that caused the Helm Chart publishing to be skipped.
**Before the commit:**
Helm Chart publishing was skipped on push of tag due to an incorrect if condition.
**After the commit:**
Helm Chart publishing should be executed on tags that start with a `v`.
=> fix(ci): fix condition for helm chart release

README.md, mqtt_exporter/main.py
Fixes/Implement: #92 
Just the ability to consume multiple topics for subscription
...
**Before the commit:**
...
**After the commit:**
...
=> MQTT_TOPIC comma separated
